sudo: false
language: clojure
lein: 2.9.3

jdk:
  - openjdk8
  - openjdk11   # Don't fall for Oracle's trick: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html
  - openjdk14

script:
  - lein do version, check, midje
