

    OBTW
     *********************************************
       Testing of comments in a nested code block
     *********************************************
    TLDR


HAI 1.2
CAN HAZ STDIO?

I HAS A VAR ITZ 1

BOTH SAEM VAR AN 1
O RLY?
  YA RLY
    BTW VAR IZ 1
  MEBBE BOTH SAEM VAR AN 2
    BTW VAR IZ 2
  MEBBE BOTH SAEM VAR AN 3
    OBTW VAR IZ 3 TLDR
  NO WAI
    BTW VAR IZ SUMFIN ELS
OIC
KTHXBYE

OBTW Finiched TLDR


