BTW Single line
OBTW Multi-line on a single line TLDR

OBTW
     **************************************************
       Testing of mixed single and multi-line comments
     **************************************************
TLDR

HAI 1.2

BTW Import some stuffs
OBTW Import some stuffs TLDR
CAN HAZ STDIO?

BTW Assign 1 to VAR
OBTW Assign 1 to VAR TLDR
I HAS A VAR ITZ 1

BTW Buh bye!
OBTW Buh bye! TLDR
KTHXBYE

BTW Uh I really meant it...
OBTW Uh I really meant it... TLDR

